version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: wetclinic_db
    environment:
      POSTGRES_USER: clinic_admin
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: wet_clinic
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
  server:
    build:
      context: .
    container_name: wetclinic_server
    ports:
      - '3001:3001'
    volumes:
      - .:/app
    depends_on:
      - db
volumes:
  db-data:
